appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
compiler_stack: comp7
conda_forge_output_validation: true
max_py_ver: '37'
max_r_ver: '35'
provider:
  linux_aarch64: azure
  linux_ppc64le: azure
travis:
  secure:
    BINSTAR_TOKEN: jsTpcF7R0Z8+dc7aKsEfc6FjpwB0Vn9v0bnk+dub6a+ljDoYonmfTdrRdUX/kYd9Z0zKmqlnm6CQNdFYWqvAArfKK6jvCP+OPQGee2YdfIjCeNSXr6nN/IhXxEoxF1xy/CeB8z1qHzQXi0eLV5sojOLl+kgZfVmXYUCFrKb9fcdfyTWaLSwmNNMW7izgQFCEyhyKx2/uXihog2yrL0ak1XgYWW1DANJDDXjs5jgvdpsQbrC5qotkPuFE+yOHEn3vU1lkODUIm3/vEJE6DRN9yu2nbdJtXZBWmfbl6OY0v0xgp/6m/BENsGUPO3P5Y3lsdLCr/pzcEjItJ2jj36K52SUqlom0YcSAvAgYDGBwO2qQakLiBUupCaNQdyymWgiuanFXZWjkQYjEGFLQTA/u2kHfmcXb5ZE/YEtxUfQyi6LS80mKjXaubu0bgH4CxHz4/RMxcFILatAN7drkMBn220Vrgnf++30okkca6v7I+6nbqkKZIKf6SjSOocsCCmdA4xVmLQ2RNcTEg4D6JpQ37Zr8wu75oINcpMOZoGawdhDVKIyjkKGtg6eJ9vcqeFj2GV/7o1+jEdRfKpZ2lN4FyhHNc0P+lxVc3veIbOJ6BdcjzIIG8tDZOeQHugV8KBTBQ900qXg7HMQ2q8k3t9p25cpe9Nh6g+rr+k3St9FzgKo=
