travis:
  secure:
    BINSTAR_TOKEN: ONPNcfWq30JS4FUAZjm8XVXVeUcNo08XYbvnmCkKX0xD8BrCbiooST5E0jHH1EKDJ5+FD4HIBK3vUi32BRY3yv4rwrMzo0WrWV5LQXwZrjcFZgDjBuTfk6RtLKEjh20WLL8L8KdxlHWb6yaJYSKuruH3EU6UirlgE8lETHUjb4dp62G3A9nrcCUYMCFUqYxWFmA0gnmdkem+cV0bBGtZCefKqN6gZYiauOXvJSqGtNyw1PQlk2uUQ901KvGa9XtJcFr4aQRxckon6S2s7DzY5+g575mME3vIRJj6gW7k5mBSkoZ4A/bK2XzF2ka99+2Q0elvmua/wF5AuhVazY2W3qGAEsOUc4TqsOWuSDYaaAMOeKHTW3pq+VegzLJ7zvyq1FZvDT89CahSPFyfrX5/l7FxzLS1+iqIiU3Fmf1KTSOa3hZ+Io/7WhHALy7gww01CMlcADWs/osJT8XYF02I3oqrnSx1H4Kw/iVNgzNzBPWGtxOLJ8dJyXtNTa12tfIJ58Sq2sjzhJDGTIQ9lkszTHtbYor0jdDcHsC1nz4OMyS4glytCNk1b4u8ZLvdkLIvEHEaupT7zwPNcnm4OV7f8x5M6fxll+EmYft3zxmIcoL3BzRWJH1ALDkx7hbcCHZpJvy5SO54rVNT9OPf5Nie4HFYiTiYJO1MUlFoX7Uh0G4=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
